server:
  port: 7001
  
eureka:
  instance:
    hostname: localhost #eureka server host name
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    